services:
  - type: web
    name: coactai-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r inter-ai-backend/requirements.txt"
    startCommand: "cd inter-ai-backend && python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000